erp/urls.py
from django.contrib import admin
from django.urls import path,include
from qlns.views import (Dsnhanvien,Profile,Logout,Phieuluonguser,Phieuluongcanhan,
                        Index,Login,Giaoviec,Nhanvientotal,Viewnhanvien,Changenhanvien,
                        Deletenhanvien,Delete_checkbox,Phieuluongupload,Getnhanvien)
from khovan.views import *
from django.conf import settings

from django.conf.urls.static import static

admin.site.index_title="Quản Trị Hệ Thống"
urlpatterns = [
    path('admin/', admin.site.urls,name="admin"),
    path('', Index.as_view(),name='index'),
    path('login/', Login.as_view(),name='login'),
    path('logout',Logout.as_view(),name='logout'),
    path('api-auth/', include('rest_framework.urls')),
    path('giao-viec/', Giaoviec.as_view(),name='giaoviec'),
    path('nhanvien/', Nhanvientotal.as_view(), name='nhanvien'),
    path('get-nhan-vien/', Getnhanvien.as_view(),name='getnhanvien'),
    path('profile/',Profile.as_view(),name='profile'),
    path('dsnhanvien/',Dsnhanvien.as_view(),name='dsnhanvien'),
    path('viewnhanvien/', Viewnhanvien.as_view(), name='viewnhanvien'),
    path('deletenhanvien/',Delete_checkbox.as_view(), name='delete-nhanvien'),
    path('phieu-luong-upload/',Phieuluongupload.as_view(), name='phieuluongupload'),
    path('nhanvien/delete/<int:nhanvien_id>',Deletenhanvien.as_view(),name='deletenhanvien'),
    path('nhan-vien/xem-nhan-vien/<int:nhanvien_id>', Changenhanvien.as_view(), name='xemnhanvien'),
    path('phieu-luong/nhan-vien/<int:nhanvien_id>', Phieuluongcanhan.as_view(), name='xemphieuluong'),
    path('phieu-luong-user', Phieuluonguser.as_view(), name='xemphieuluonguser'),
    path('nhap-hang/',Nhaphangs.as_view(),name="nhap-hang"),
    path('nhap-hang/<int:code_id>',Viewphieunhap.as_view(),name='view-nhap-hang'),
    path('phieu-nhap-kho/',Phieunhapkho.as_view(),name="phieu-nhap-kho"),
    path('load-courses/', load_courses.as_view(), name='ajax_load_courses'),
    path('quan-ly-nhap-hang',Quanlynhaphang.as_view(),name="quan-ly-nhap-hang"),
    path('nhap-hang-chua-duyet',Nhaphangchuaduyet.as_view(),name='nhaphangchuaduyet'),
    path('nhap-hang-chua-duyet-gap',Nhaphangchuaduyetgap.as_view(),name='nhaphangchuaduyetgap'),
    path('duyet-nhap-hang/<int:code_id>',Duyetnhaphang.as_view(),name='duyetnhaphang'),
    path('xuat-hang/',Xuathang.as_view(),name="xuat-hang"),
    path('ton-kho/',Tonkho.as_view(),name="ton-kho"),
    path('dieu-chuyen-kho/',Dieuchuyenkho.as_view(),name="dieu-chuyen-kho"),
              ]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

khovan/models.py
from django.db import models
from django.utils import timezone
from django.contrib import admin
from django.utils.html import format_html
from django.contrib.auth.models import AbstractUser,User
from qlns.models import Nhanvien
# Create your models here.


class Gas(models.Model):
    tengas = models.CharField(default='',max_length=100,blank=False,null=False,verbose_name='Loại Gas')
    mota = models.CharField(max_length=500,blank=True,null=True,verbose_name='Mô tả (có thể bỏ trống)')
    class Meta:
        verbose_name = "LOẠI GAS"
        verbose_name_plural = 'LOẠI GAS'

    def __str__(self):
        return self.tengas
class Loaimay(models.Model):
    tenloai = models.CharField(default='',max_length=100,blank=False,null=False,verbose_name='Loại Máy')
    mota = models.CharField(max_length=500,blank=True,null=True,verbose_name='Mô tả (có thể bỏ trống)')
    class Meta:
        verbose_name = "LOẠI MÁY "
        verbose_name_plural = 'LOẠI MÁY '

    def __str__(self):
        return self.tenloai

class Congsuat(models.Model):
    tencongsuat = models.CharField(default='',max_length=100,blank=False,null=False,verbose_name=' Công suất ')
    mota = models.CharField(max_length=500,blank=True,null=True,verbose_name='Mô tả (có thể bỏ trống)')
    class Meta:
        verbose_name = "CÔNG SUẤT "
        verbose_name_plural = 'CÔNG SUẤT '

    def __str__(self):
        return self.tencongsuat

class Hemay(models.Model):
    tenhemay = models.CharField(default='',max_length=100,blank=False,null=False,verbose_name=' Hệ Máy ')
    mota = models.CharField(max_length=500,blank=True,null=True,verbose_name='Mô tả (có thể bỏ trống)')
    class Meta:
        verbose_name = "HỆ MÁY"
        verbose_name_plural = 'HỆ MÁY'

    def __str__(self):
        return self.tenhemay

class Nganhhang(models.Model):
    tennghanhhang = models.CharField(default='',max_length=100,blank=False,null=False,verbose_name='Tên Nghành Hàng ')
    mota = models.CharField(max_length=500,blank=True,null=True,verbose_name='Mô tả (có thể bỏ trống)')
    class Meta:
        verbose_name = "NGÀNH HÀNG "
        verbose_name_plural = 'NGÀNH HÀNG '

    def __str__(self):
        return self.tennghanhhang
class Hangsx(models.Model):
    tenhangsx = models.CharField(default='',max_length=100,blank=False,null=False,verbose_name='Tên Hãng ')
    mota = models.CharField(max_length=500,blank=True,null=True,verbose_name='Mô tả (có thể bỏ trống)')
    class Meta:
        verbose_name = "HÃNG SX "
        verbose_name_plural = 'HÃNG SX '

    def __str__(self):
        return self.tenhangsx


class Hanghoa(models.Model):
    code = models.IntegerField(default=0,unique=True)
    tenhanghoa = models.CharField(default='',max_length=100,blank=False,null=False,verbose_name='Tên Hàng Hoá (Dàn Lạnh/ Dàn Nóng.)')
    hangsx = models.ForeignKey(Hangsx,on_delete=models.CASCADE,verbose_name='Hãng Sản Xuất')
    nganhhang = models.ForeignKey(Nganhhang,on_delete=models.CASCADE,verbose_name='Danh Mục')
    hemay = models.ForeignKey(Hemay,on_delete=models.CASCADE,verbose_name='Hệ Máy ')
    congsuat = models.ForeignKey(Congsuat,on_delete=models.CASCADE,verbose_name='Công Suất')
    loaimay =  models.ForeignKey(Loaimay,on_delete=models.CASCADE,verbose_name='Loại Máy ')
    gas = models.ForeignKey(Gas,on_delete=models.CASCADE,verbose_name='Loại Gas ')
    giavon = models.IntegerField(default='0',blank=True,null=True,verbose_name='Giá Vốn ')
    mota = models.CharField(max_length=500,blank=True,null=True,verbose_name='Mô tả (có thể bỏ trống)')
    class Meta:
        verbose_name = "HÀNG HOÁ "
        verbose_name_plural = 'HÀNG HOÁ'

    def __str__(self):
        return self.tenhanghoa

class Khohang(models.Model):
    tenkho = models.CharField(max_length=200,blank=False,null=False,verbose_name='Tên Kho')
    diachi = models.CharField(max_length=500,blank=True,null=True,verbose_name='Địa Chỉ')
    class Meta:
        verbose_name = "KHO HÀNG "
        verbose_name_plural = 'KHO HÀNG'

    def __str__(self):
        return self.tenkho

class Thukho_Khohang(models.Model):
    nhanvien = models.ForeignKey(Nhanvien,on_delete=models.CASCADE)
    kho = models.ForeignKey(Khohang,on_delete=models.CASCADE)
    class Meta:
        verbose_name = "THỦ KHO"
        verbose_name_plural = 'THỦ KHO'

    def __str__(self):
        return self.nhanvien

class Nhaphang(models.Model):
    hanghoa = models.ForeignKey(Hanghoa, on_delete=models.CASCADE,verbose_name='Tên Hàng Hoá')
    soluong = models.IntegerField(default=0,blank=True,verbose_name='Số Lượng')
    kho = models.ForeignKey(Khohang,on_delete=models.CASCADE)
    tinhtrang = models.BooleanField(verbose_name='Tình Trạng -( Check Nếu Hàng Đã Thực Nhập )')

    class Meta:
        verbose_name = "NHẬP HÀNG "
        verbose_name_plural = 'NHẬP HÀNG'

    def __str__(self):
        return self.hanghoa


class Nhacungcap(models.Model):
    tennhacungcap =  models.CharField(max_length=200,blank=False,null=False,verbose_name='Tên Nhà Cung Cấp')
    diachinhacungcap =  models.CharField(max_length=200,blank=False,null=False,verbose_name='Địa chỉ nhà cung cấp')
    diachikhonhacungcap = models.CharField(max_length=200,blank=False,null=False,verbose_name='Địa chỉ nhà cung cấp')
    nhanvienquanly = models.ForeignKey(Nhanvien ,on_delete=models.CASCADE, verbose_name='Tên Nhân Viên Quản Lý')
    hanmuccongno = models.FloatField(default=0, blank=True,null=True,verbose_name='Hạn mức ')

    def __str__(self):
        return self.tennhacungcap

    class Meta:
        verbose_name = "NHÀ CUNG CẤP "
        verbose_name_plural = 'NHÀ CUNG CẤP'


class Phieunhaphang(models.Model):

    code  =  models.CharField(max_length=200,blank=False,null=False,verbose_name='Barcode',unique=True)
    nhacungcap  =  models.ForeignKey(Nhacungcap, on_delete = models.CASCADE, verbose_name='Nhà cung cấp' )
    noidung = models.JSONField(blank=False,null=False,verbose_name='Nội Dung ')
    username = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Tài Khoản')
    nhanvien =  models.CharField(max_length=200,blank=True,null=True,verbose_name='Tên Kinh doanh(không  điền trường này)')
    kho = models.ForeignKey(Khohang, on_delete=models.CASCADE, verbose_name='Kho')
    tinhtrang = models.BooleanField(verbose_name='Duyệt')
    tuchoi = models.BooleanField(verbose_name='Từ Chối')
    thoigiantao = models.DateField()
    thoigiannhanhang = models.DateField()
    ghichu = models.CharField(default=".",max_length=200,blank=False,null=False,verbose_name='Ghi Chú  ')
    phanhoi =  models.CharField(default=".",max_length=200,blank=False,null=False,verbose_name='Phản Hồi  ')

    class Meta:
        verbose_name = "PHIẾU NHẬP XUẤT HÀNG "
        verbose_name_plural = 'PHIẾU NHẬP XUẤT HÀNG'

    def __str__(self):
        return self.code

class Xuathang(models.Model):

    hanghoa = models.ForeignKey(Hanghoa, on_delete=models.CASCADE, verbose_name='Tên Hàng Hoá')
    soluong = models.IntegerField(default=0, verbose_name='Số Lượng')
    kho = models.ForeignKey(Khohang, on_delete=models.CASCADE, verbose_name='Tên Kho')

    tinhtrang = models.BooleanField(verbose_name='Tình Trạng -(Check Nếu Hàng Đã Thực Xuất)')

    class Meta:
        verbose_name = "XUẤT HÀNG "
        verbose_name_plural = 'XUẤT HÀNG'

    def __str__(self):
        return self.hanghoa



class Ton_kho(models.Model):
    hanghoa = models.ForeignKey(Hanghoa, on_delete=models.CASCADE, verbose_name='Tên Hàng Hoá')
    soluongnhap = models.IntegerField(default=0, verbose_name='Số Lượng Nhập')
    soluongxuat = models.IntegerField(default=0, verbose_name='Số Lượng Xuất')
    kho = models.ForeignKey(Khohang, on_delete=models.CASCADE, verbose_name='Tên Kho')

    def __str__(self):
        return self.hanghoa

    class Meta:
        verbose_name = "TỒN KHO "
        verbose_name_plural = 'TỒN KHO'

templates/demso.html
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<form method="post">
    <input type="text" id="the_input_id">
    <input type="text" id="the_input_id1">
    <input type="text" id="kq" name="kq">
</form>

<div   id="total"></div>

<script type="text/javascript">
  
  $(function() {
    

    $('#the_input_id').keyup(function() {  
        updateTotal();
    });
    
    $('#the_input_id1').keyup(function() {  
        updateTotal();
    });
    
    var updateTotal = function () {
      var input1 = parseInt($('#the_input_id').val());
      var input2 = parseInt($('#the_input_id1').val());
      var tong =input1 * input2
     
      $("input[type=text][name=kq]" ).val(tong);
      
    };

    var output_total = $('#total');

    var total = firstInput+firstInput1;

   output_total.text(total);

 });
</script>

templates/dieuchuyenkho.html
{% extends 'base.html'%}{%load static%}{%block dieuchuyenkho%}{%endblock%}

templates/duyetnhaphang.html
{% extends 'base.html'%}
{%load static%}

{%block duyetnhaphang%}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">

                        <li class="breadcrumb-item active">
                          
                      </li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title badge badge-pill badge-info">
                              DUYỆT NHẬP HÀNG
                            </h3>
                        </div>
                        <!-- /.card-header -->

                        <!-- /.card-body -->
                        
                        <div style="padding:30px;">
                        <form action=" " method="POST" class="form-horizontal" role="form">
                                {% csrf_token %}                   
                               <div><label>Nhân viên khinh danh  :</label> {{phieunhaphang.nhanvien}}</div>
                               <div><label>Ngầy Tạo   :</label> {{phieunhaphang.thoigiantao}}</div>
                               <div><label>Ngày Giao Dự Kiến  :</label> {{phieunhaphang.thoigiannhanhang}}</div>
                               <div><label>Kho   :</label> {{phieunhaphang.kho}}</div>
                               <div><label>Ghi Chú Kinh Doanh   :</label> {{phieunhaphang.ghichu}}</div>
                               <div>
                                   <table class="table table-hover table-bordered">
                                       <thead>
                                           <tr>
                                               
                                               <th>Tên Sản Phẩm</th>
                                               <th>Số Lượng</th>
                                               <th>Đơn Giá</th>
                                               <th>Thành Tiền</th>
                                           </tr>
                                       </thead>
                                       <tbody>
                                           <tr>
                                               <td>{{phieunhaphang.noidung.tenhang_1}}</td>
                                               <td>{{phieunhaphang.noidung.soluong_1}}</td>
                                               <td>{{phieunhaphang.noidung.dongia_1}}</td>
                                               <td></td>
                                           </tr>
                                           {% if phieunhaphang.noidung.tenhang_2  %}
                                           <tr>
                                               <td>{{phieunhaphang.noidung.tenhang_2}}</td>
                                               <td>{{phieunhaphang.noidung.soluong_2}}</td>
                                               <td>{{phieunhaphang.noidung.dongia_2}}</td>
                                               <td></td>
                                           </tr>
                                           {%endif%}
                                           {% if phieunhaphang.noidung.tenhang_3  %}
                                           <tr>
                                               <td>{{phieunhaphang.noidung.tenhang_3}}</td>
                                               <td>{{phieunhaphang.noidung.soluong_3}}</td>
                                               <td>{{phieunhaphang.noidung.dongia_3}}</td>
                                               <td></td>
                                           </tr>
                                           {%endif%}
                                           {% if phieunhaphang.noidung.tenhang_4  %}
                                           <tr>
                                               <td>{{phieunhaphang.noidung.tenhang_4}}</td>
                                               <td>{{phieunhaphang.noidung.soluong_4}}</td>
                                               <td>{{phieunhaphang.noidung.dongia_4}}</td>
                                               <td></td>
                                           </tr>
                                           {%endif%}
                                       </tbody>
                                   </table>
                               </div>
                               <div><label>Phản Hồi Cho Kinh Danh   :</label>{{form.phanhoi}}<br>
                               
                                   <div class="radio">
                                       <label style="color:green;" id='nonhiden'>
                                         {{form.tinhtrang}}
                                           Duyệt Đơn Hàng
                                       </label>
                                       <br>
                                       <label style="color:red; " id='hiden'>
                                            {{form.tuchoi}}
                                           Từ Chối Đơn Hàng
                                       </label>
                                   </div>
                                   <br>

                                <div class="form-group">

                                    <div class="col-sm-10 col-sm-offset-2"><br>
                                      <button type="button" id="load" class="btn btn btn-lg btn-default">Refresh</button>
                                        <button type="submit" class="btn btn-lg btn-primary">Save</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                        </div>
                    </div>
                    <!-- /.card -->

                   
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </section>
    <!-- /.content -->




</div>

<script>
    $(document).ready(function(){
        $("#id_tinhtrang").change('checked',function(){
          $('#hiden').hide();
        });
    
          $("#id_tuchoi").change('checked',function(){
          $('#nonhiden').hide();
        });

           $('#load').click(function() {
         location.reload();
           });

    });

    
</script>
{%endblock%}

templates/load_hanghoa.html
{% for course in courses %}<option value="{{ course.pk }}">{{ course.tenhanghoa }}</option>{% endfor %}{% for course in courses2 %}<option value="{{ course.pk }}">{{ course.tenhanghoa }}</option>{% endfor %}{% for course in courses3 %}<option value="{{ course.pk }}">{{ course.tenhanghoa }}</option>{% endfor %}{% for course in courses4 %}<option value="{{ course.pk }}">{{ course.tenhanghoa }}</option>{% endfor %}{% for item in nhanvien %}<option value="{{ item.pk }}">{{ item.sdt }}</option>{% endfor %}

templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>DONG SAPA  | Log in </title>

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css'%}">
  <!-- icheck bootstrap -->
  <link rel="stylesheet" href="{% static 'plugins/icheck-bootstrap/icheck-bootstrap.min.css'%}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css'%}">
</head>
<body class="hold-transition login-page">
<div class="login-box">
  <!-- /.login-logo -->
  <div class="card card-outline card-primary">
    <div class="card-header text-center">
      <a href="../../login/" class="h1"><b><img src="{%static 'img/Logo-web-dongsapa.png' %}" alt=""  width="200" height="40">  </b></a>
    </div>
    <div class="card-body">
      <p class="login-box-msg">ĐĂNG NHẬP</p>

      <form action="{% url 'login' %}" method="post">
         {% csrf_token %}
        <div class="input-group mb-3">
          <input type="text" class="form-control" name="username" placeholder="Tên Đăng Nhập">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-envelope"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
          <input type="password" class="form-control" name="password" placeholder="Password">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-8">
            <div class="icheck-primary">
              <input type="checkbox" id="remember">
              <label for="remember">
                Lưu thông tin đăng nhập
              </label>
            </div>
          </div>
          <!-- /.col -->
          <div class="col-4">
            <button type="submit" class="btn btn-primary btn-block">Sign In</button>
          </div>
          <!-- /.col -->
        </div>
      </form>


      <!-- /.social-auth-links -->


    </div>
    <!-- /.card-body -->
  </div>
  <!-- /.card -->
</div>
<!-- /.login-box -->

<!-- jQuery -->
<script src="{% static 'plugins/jquery/jquery.min.js'%}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js'%}"></script>
<!-- AdminLTE App -->
<script src="{% static dist/js/adminlte.min.js'}"></script>
</body>
</html>

templates/quanly.html
{% extends 'base.html'%}
{%load static%}
{%block quanlykho%}


<div class="content-wrapper">
    <section class="content">
        <div class="container-fluid">
            <br>


            <div class="panel panel-default">
                <!-- Default panel contents -->


                <!-- Table -->
                <table class="table">
                    <thead>
                    <tr>
                        <th>Quản Lý Đơn Hàng Nhập</th>
                    </tr>

                    </thead>
                    <tbody>

                    <tr>
                        <td>


                            <div class="row">
                                <div class="col-lg-3 col-6">
                                    <!-- small box -->
                                    <div class="small-box bg-danger">
                                        <div class="inner">
                                            <h3>{{demph_chua_duyet_gap}}</h3>

                                            <p>Đơn Nhập Hàng Gấp</p>
                                        </div>
                                        <div class="icon">
                                            <i class="ion ion-bag"></i>
                                        </div>
                                        <a href="{% url 'nhaphangchuaduyetgap' %}" class="small-box-footer"> Xem <i
                                                class="fas fa-arrow-circle-right"></i></a>
                                    </div>
                                </div>
                                <!-- ./col -->
                                <div class="col-lg-3 col-6">
                                    <!-- small box -->
                                    <div class="small-box bg-warning">
                                        <div class="inner">
                                            <h3>{{demph_chua_duyet}}</h3>

                                            <p>Chờ Phê Duyệt</p>
                                        </div>
                                        <div class="icon">
                                            <i class="ion ion-stats-bars"></i>
                                        </div>
                                        <a href="{% url 'nhaphangchuaduyet' %}" class="small-box-footer">Xem <i
                                                class="fas fa-arrow-circle-right"></i></a>
                                    </div>
                                </div>
                                <!-- ./col -->
                                <div class="col-lg-3 col-6">
                                    <!-- small box -->
                                    <div class="small-box bg-success">
                                        <div class="inner">
                                            <h3>{{demph_duyet}}</h3>

                                            <p>Đã Phê Duyệt</p>
                                        </div>
                                        <div class="icon">
                                            <i class="ion ion-person-add"></i>
                                        </div>
                                        <a href="#" class="small-box-footer">Xem <i
                                                class="fas fa-arrow-circle-right"></i></a>
                                    </div>
                                </div>
                                <!-- ./col -->
                                <div class="col-lg-3 col-6">
                                    <!-- small box -->
                                    <div class="small-box bg-sercondary">
                                        <div class="inner">
                                            <h3>65</h3>

                                            <p>Đơn Từ Chối</p>
                                        </div>
                                        <div class="icon">
                                            <i class="ion ion-pie-graph"></i>
                                        </div>
                                        <a href="#" class="small-box-footer">Xem<i
                                                class="fas fa-arrow-circle-right"></i></a>
                                    </div>
                                </div>
                                <!-- ./col -->
                            </div>

                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>


    </section>


</div>


{%endblock%}

templates/xuathang.html
{% extends 'base.html'%}{%load static%}{%block xuathang%}{%endblock%}